services:
  - type: web
    name: sports-card-analyzer-api
    env: node
    buildCommand: |
      sudo apt-get update && \
      sudo apt-get install -y firefox-esr xvfb libgtk-3-0 libasound2 libx11-xcb1 libxss1 libnss3 && \
      npm install && \
      npx playwright install firefox && \
      npx playwright install-deps
    startCommand: |
      sudo Xvfb :99 -screen 0 1024x768x16 &
      sleep 1
      node server/server.js
    plan: starter
    region: ohio
    branch: main
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISPLAY
        value: ":99"
      - key: PORT
        value: "3000"
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://sports-card-analyzer.netlify.app 