services:
  - type: web
    name: sports-card-analyzer-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: ohio
    branch: main
    healthCheckPath: /
    numInstances: 1
    buildCommand: docker build -t sports-card-analyzer-api .
    startCommand: docker run -p 3000:3000 sports-card-analyzer-api
    buildFilter:
      paths:
      - server/**
      - Dockerfile
      - package.json
      - package-lock.json
    port: 3000
    domains:
      - sports-card-analyzer-api.onrender.com
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /ms-playwright
      - key: DISPLAY
        value: ":99"
      - key: PORT
        value: "3000"
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: FRONTEND_URL
        value: https://sports-card-analyzer.netlify.app 