[build]
  functions = "netlify/functions"
  publish = "public"
  command = "mkdir -p public && echo '{}' > public/index.json"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true 